# ===============================
# PING WENCHAO 226969
# Database Configuration - Routing to UPM Oracle Server (Lab 11)
# ===============================

# 1. Oracle Database URL (fsktmdbora server, port 1521, SID FSKTM)
spring.datasource.url=jdbc:oracle:thin:@//fsktmdbora.upm.edu.my:1521/FSKTM

# 2. Institutional Oracle Credentials
spring.datasource.username=D226969
spring.datasource.password=226969

# 3. Oracle JDBC Driver
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# 4. Hibernate Dialect for Oracle 12c syntax generation
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

# ===============================
# Hibernate & Data Initialization
# ===============================

# Automatically generate or update database tables based on Java Entities
spring.jpa.hibernate.ddl-auto=update

# Print SQL statements to the console for debugging
spring.jpa.show-sql=true

# Data Initialization - Run data.sql AFTER Hibernate creates the tables
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always