# PING WENCHAO 226969
# Database Configuration - Routing to XAMPP MySQL Server
spring.datasource.url=jdbc:mysql://localhost:3306/lab9db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate Configuration - Automatically generate or update database tables based on Java Entities
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Data Initialization - Run data.sql AFTER Hibernate creates the tables
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always